# Generated by Django 2.2.5 on 2019-09-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
