# Generated by Django 2.2.5 on 2019-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190923_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
