# Generated by Django 2.2.5 on 2020-02-12 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190926_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(blank=True, default='o', max_length=1),
        ),
    ]
